name: Rebase on Upstream

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: siriume/rebase-upstream-action@master
